apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-test-api
  description: Testing the API component
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: my-test-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
      /test:
        get:
          summary: Just a test
